# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget lib-xtb-static lib-xtb-shared xtb-exe)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target lib-xtb-static
add_library(lib-xtb-static STATIC IMPORTED)

set_target_properties(lib-xtb-static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/include;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/include"
  INTERFACE_LINK_LIBRARIES "/data/user/0/ru.iiec.pydroid3/app_HOME/libs-aarch64/libblas.a;/data/user/0/ru.iiec.pydroid3/app_HOME/libs-aarch64/liblapack.a;\$<\$<BOOL:FALSE>:OpenMP::OpenMP_Fortran>;mctc-lib::mctc-lib;tblite::tblite"
)

# Create imported target lib-xtb-shared
add_library(lib-xtb-shared SHARED IMPORTED)

set_target_properties(lib-xtb-shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/include;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/include"
  INTERFACE_LINK_LIBRARIES "/data/user/0/ru.iiec.pydroid3/app_HOME/libs-aarch64/libblas.a;/data/user/0/ru.iiec.pydroid3/app_HOME/libs-aarch64/liblapack.a;\$<\$<BOOL:FALSE>:OpenMP::OpenMP_Fortran>;mctc-lib::mctc-lib;tblite::tblite"
)

# Create imported target xtb-exe
add_executable(xtb-exe IMPORTED)

# Import target "lib-xtb-static" for configuration "RelWithDebInfo"
set_property(TARGET lib-xtb-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lib-xtb-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/libxtb.a"
  )

# Import target "lib-xtb-shared" for configuration "RelWithDebInfo"
set_property(TARGET lib-xtb-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(lib-xtb-shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/libxtb.so.6.6.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libxtb.so.6"
  )

# Import target "xtb-exe" for configuration "RelWithDebInfo"
set_property(TARGET xtb-exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(xtb-exe PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
