# CMake generated Testfile for 
# Source directory: /data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit
# Build directory: /data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(xtb/atomlist "xtb-tester" "atomlist")
set_tests_properties(xtb/atomlist PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/coordinationnumber "xtb-tester" "coordinationnumber")
set_tests_properties(xtb/coordinationnumber PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/coulomb "xtb-tester" "coulomb")
set_tests_properties(xtb/coulomb PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/dftd3 "xtb-tester" "dftd3")
set_tests_properties(xtb/dftd3 PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/dftd4 "xtb-tester" "dftd4")
set_tests_properties(xtb/dftd4 PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/docking "xtb-tester" "docking")
set_tests_properties(xtb/docking PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/eeq "xtb-tester" "eeq")
set_tests_properties(xtb/eeq PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/gfn0 "xtb-tester" "gfn0")
set_tests_properties(xtb/gfn0 PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/gfn1 "xtb-tester" "gfn1")
set_tests_properties(xtb/gfn1 PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/gfn2 "xtb-tester" "gfn2")
set_tests_properties(xtb/gfn2 PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/gfnff "xtb-tester" "gfnff")
set_tests_properties(xtb/gfnff PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/hessian "xtb-tester" "hessian")
set_tests_properties(xtb/hessian PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/iff "xtb-tester" "iff")
set_tests_properties(xtb/iff PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/latticepoint "xtb-tester" "latticepoint")
set_tests_properties(xtb/latticepoint PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/molecule "xtb-tester" "molecule")
set_tests_properties(xtb/molecule PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/oniom "xtb-tester" "oniom")
set_tests_properties(xtb/oniom PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/pbc-tools "xtb-tester" "pbc-tools")
set_tests_properties(xtb/pbc-tools PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/peeq "xtb-tester" "peeq")
set_tests_properties(xtb/peeq PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/repulsion "xtb-tester" "repulsion")
set_tests_properties(xtb/repulsion PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/symmetry "xtb-tester" "symmetry")
set_tests_properties(xtb/symmetry PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/tblite "xtb-tester" "tblite")
set_tests_properties(xtb/tblite PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/thermo "xtb-tester" "thermo")
set_tests_properties(xtb/thermo PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/vertical "xtb-tester" "vertical")
set_tests_properties(xtb/vertical PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/wsc "xtb-tester" "wsc")
set_tests_properties(xtb/wsc PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;77;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/Argparser_print_version "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--version")
set_tests_properties(xtb/Argparser_print_version PROPERTIES  _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;88;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/Argparser_print_help "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--help")
set_tests_properties(xtb/Argparser_print_help PROPERTIES  _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;89;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/Argparser_print_license "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--license")
set_tests_properties(xtb/Argparser_print_license PROPERTIES  _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;90;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/Info "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "info" "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/assets/inputs/coord/caffeine.coord" "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/assets/inputs/coord/quartz.3d.coord" "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/assets/inputs/vasp/ammonia.vasp" "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/assets/inputs/xyz/taxol.xyz")
set_tests_properties(xtb/Info PROPERTIES  _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;91;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/Singlepoint "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--strict" "--norestart" "--namespace" "test1")
set_tests_properties(xtb/Singlepoint PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;97;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/IP/EA "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--gfn" "2" "--vipea" "--strict" "--norestart" "--namespace" "test2")
set_tests_properties(xtb/IP/EA PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;98;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/GFN0-xTB "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--gfn" "0" "--strict" "--norestart" "--namespace" "test3")
set_tests_properties(xtb/GFN0-xTB PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;99;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/GFN1-xTB "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--gfn" "1" "--strict" "--norestart" "--namespace" "test4")
set_tests_properties(xtb/GFN1-xTB PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;100;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/GFN2-xTB/GBSA "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--gfn" "2" "--strict" "--gbsa" "h2o" "--norestart" "--namespace" "test5")
set_tests_properties(xtb/GFN2-xTB/GBSA PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;101;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
add_test(xtb/GFN2-FF "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/build/xtb" "--coffee" "--gfnff" "--strict" "--norestart" "--namespace" "test6")
set_tests_properties(xtb/GFN2-FF PROPERTIES  ENVIRONMENT "XTBPATH=/data/user/0/ru.iiec.pydroid3/app_HOME/xtb" _BACKTRACE_TRIPLES "/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;102;add_test;/data/user/0/ru.iiec.pydroid3/app_HOME/xtb/test/unit/CMakeLists.txt;0;")
